#!/usr/bin/python3
# -*- coding: utf-8 -*-

''' 
Script to run after `pkgdown::build_site()`:

- Fixes paths in html docs files generated by pkgdown.
- Adds `/docs/.nojekyll` for githubpages.

'''

import os
import sys
import fileinput

def replace(str_wrong, str_right, filename):
    ''' Replaces all occurrences of str_wrong with str_right in filename. '''

    path = './docs/articles/'
    for i, line in enumerate(fileinput.input(path+filename, inplace=1)):
        sys.stdout.write(line.replace(str_wrong, str_right))

if __name__ == '__main__':
    replace('"../../reference', '"../reference', 'introduction_to_responsesR.html')
    replace('<img src="reference', '<img src="../reference', 'replicating_survey_data.html')
    replace('<img src="reference', '<img src="../reference', 'simulating_survey_data.html')

    # add .nojekyll to docs for githubpages
    os.system("touch ./docs/.nojekyll")

    print("Done.")