#!/usr/bin/python3
# -*- coding: utf-8 -*-

''' 
Script to run after `pkgdown::build_site()`:

- Fixes paths in html docs files generated by pkgdown.
- Adds alt text to images in README.md file.
- Adds `/docs/.nojekyll` for githubpages.
- Adds meta description to index.html
'''

import os
import sys
import fileinput

def replace(str_wrong, str_right, pathfilename):
    ''' Replaces all occurrences of str_wrong with str_right in filename. '''
    for i, line in enumerate(fileinput.input(pathfilename, inplace=1)):
        sys.stdout.write(line.replace(str_wrong, str_right))

def add_meta():
    filename = './docs/index.html'
    meta_line = '<meta name="description" content="Generate Likert-scale responses in R. responsesR provides an easy framework to simulate survey data, specifically Likert items." />'

    with open(filename, 'r') as f:
        in_file = f.readlines()

    out_file = []
    for line in in_file:
        out_file.append(line)
        if '</title>' in line:
            out_file.append(meta_line)    
            
    with open(filename, 'w') as f:
        f.writelines(out_file)    

if __name__ == '__main__':
    replace('"../../reference', '"../reference', './docs/articles/introduction_to_responsesR.html')
    replace('<img src="reference', '<img src="../reference', './docs/articles/replicating_survey_data.html')
    replace('<img src="reference', '<img src="../reference', './docs/articles/simulating_survey_data.html')

    str_wrongs = ['<img src="./man/figures/articles/courses_grouped_bar_chart.svg" width="100%" />',
                '<img src="./man/figures/articles/courses_stacked_bar_chart.svg" width="100%" />',
                '<img src="./man/figures/articles/agree_items_correlations_comparison.svg" width="100%" />',
                '<img src="./man/figures/articles/agreeableness_grouped_boxplot.svg" width="100%" />']

    str_rights = ['<img src="./man/figures/articles/courses_grouped_bar_chart.svg" width="100%" alt="Courses grouped bar chart" />',
                '<img src="./man/figures/articles/courses_stacked_bar_chart.svg" width="100%" alt="Courses stacked bar chart" />',
                '<img src="./man/figures/articles/agree_items_correlations_comparison.svg" width="100%" alt="Agreeableness items correlations comparison" />',
                '<img src="./man/figures/articles/agreeableness_grouped_boxplot.svg" width="100%" alt="Agreeableness grouped boxplot" />']

    for i in range(len(str_wrongs)):
        replace(str_wrongs[i], str_rights[i], './README.md')

    str_wrong = '<img src="./reference/figures/logo.png" align="right" height="160" style="float:right; height:160px;">'
    str_right = '<img src="./reference/figures/logo.png" alt="Package logo" align="right" height="160" style="float:right; height:160px;">'
    replace(str_wrong, str_right, './docs/index.html')

    # add .nojekyll to docs for githubpages
    os.system("touch ./docs/.nojekyll")

    add_meta()

    print("Done.")